// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnomiAssignmentReal.Data;

#nullable disable

namespace SnomiAssignmentReal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121032009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SnomiAssignmentReal.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "C100",
                            CategoryDescription = "Hearty breakfast options served all day",
                            CategoryName = "All-Day Breakfast"
                        },
                        new
                        {
                            CategoryId = "C101",
                            CategoryDescription = "Artisan sandwiches and cheesy toasties",
                            CategoryName = "Sandwiches & Toasties"
                        },
                        new
                        {
                            CategoryId = "C102",
                            CategoryDescription = "Fresh salads and nutrient-rich grain bowls",
                            CategoryName = "Salads & Healthy Bowls"
                        },
                        new
                        {
                            CategoryId = "C103",
                            CategoryDescription = "House-made cakes, tarts, and sweet treats",
                            CategoryName = "Signature Desserts"
                        },
                        new
                        {
                            CategoryId = "C104",
                            CategoryDescription = "Hot and iced classic café beverages",
                            CategoryName = "Coffee & Tea"
                        },
                        new
                        {
                            CategoryId = "C105",
                            CategoryDescription = "	Fruity smoothies, milkshakes, and fizzy mocktails",
                            CategoryName = "Smoothies & Coolers"
                        },
                        new
                        {
                            CategoryId = "C106",
                            CategoryDescription = "Freshly baked croissants, muffins, and pastries",
                            CategoryName = "Baked Goods & Pastries"
                        },
                        new
                        {
                            CategoryId = "C107",
                            CategoryDescription = "Limited-time festive or themed meal sets",
                            CategoryName = "Seasonal Specials"
                        });
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerEmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerFullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CustomerProfileImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CustomerRewardPoints")
                        .HasColumnType("int");

                    b.Property<string>("CustomerUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCustomerLoggedIn")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.CustomerOrder", b =>
                {
                    b.Property<string>("CustomerOrderId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("EmailReceiptSentAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetPayableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OrderTotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RewardPointsAwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RewardPointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("RewardPointsRedeemed")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerOrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.Function", b =>
                {
                    b.Property<string>("FunctionId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FunctionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FunctionId");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            FunctionId = "F100",
                            FunctionDescription = "Add, edit, delete menu items",
                            FunctionName = "Manage Menu"
                        },
                        new
                        {
                            FunctionId = "F101",
                            FunctionDescription = "View and change status of orders",
                            FunctionName = "View CustomerOrders"
                        },
                        new
                        {
                            FunctionId = "F102",
                            FunctionDescription = "Access past orders",
                            FunctionName = "Order History"
                        },
                        new
                        {
                            FunctionId = "F103",
                            FunctionDescription = "Access report",
                            FunctionName = "View Report"
                        },
                        new
                        {
                            FunctionId = "F104",
                            FunctionDescription = "Manage accounts",
                            FunctionName = "Manage accounts"
                        });
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.MenuItem", b =>
                {
                    b.Property<string>("MenuItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailableForOrder")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemCalories")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MenuItemImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MenuItemUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.OrderCustomizationSettings", b =>
                {
                    b.Property<string>("MenuItemCustomizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CustomizationAdditionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomizationDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EligibleCategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MenuItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MenuItemCustomizationId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderDetailId");

                    b.ToTable("OrderCustomizationSettings");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MenuItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoginEmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserProfileImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserRoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.UserRole", b =>
                {
                    b.Property<string>("UserRoleId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = "UR100",
                            RoleDescription = "System Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            UserRoleId = "UR101",
                            RoleDescription = "Cafe Staff",
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.UserRoleFunction", b =>
                {
                    b.Property<string>("UserRoleFunctionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FunctionId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsFunctionEnabledForRole")
                        .HasColumnType("bit");

                    b.Property<string>("UserRoleId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserRoleFunctionId");

                    b.HasIndex("FunctionId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("UserRoleFunctions");

                    b.HasData(
                        new
                        {
                            UserRoleFunctionId = "URF100",
                            FunctionId = "F100",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR100"
                        },
                        new
                        {
                            UserRoleFunctionId = "URF101",
                            FunctionId = "F101",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR100"
                        },
                        new
                        {
                            UserRoleFunctionId = "URF102",
                            FunctionId = "F102",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR100"
                        },
                        new
                        {
                            UserRoleFunctionId = "URF103",
                            FunctionId = "F103",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR100"
                        },
                        new
                        {
                            UserRoleFunctionId = "URF104",
                            FunctionId = "F104",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR100"
                        },
                        new
                        {
                            UserRoleFunctionId = "URF200",
                            FunctionId = "F101",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR101"
                        },
                        new
                        {
                            UserRoleFunctionId = "URF201",
                            FunctionId = "F102",
                            IsFunctionEnabledForRole = true,
                            UserRoleId = "UR101"
                        });
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.CustomerOrder", b =>
                {
                    b.HasOne("SnomiAssignmentReal.Models.Customer", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.MenuItem", b =>
                {
                    b.HasOne("SnomiAssignmentReal.Models.Category", "Category")
                        .WithMany("CategoryMenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.OrderCustomizationSettings", b =>
                {
                    b.HasOne("SnomiAssignmentReal.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemCustomizations")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnomiAssignmentReal.Models.OrderDetail", null)
                        .WithMany("AppliedCustomizations")
                        .HasForeignKey("OrderDetailId");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.OrderDetail", b =>
                {
                    b.HasOne("SnomiAssignmentReal.Models.CustomerOrder", "CustomerOrder")
                        .WithMany("CustomerOrderDetails")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnomiAssignmentReal.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemOrderDetails")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.User", b =>
                {
                    b.HasOne("SnomiAssignmentReal.Models.UserRole", "UserRole")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.UserRoleFunction", b =>
                {
                    b.HasOne("SnomiAssignmentReal.Models.Function", "Function")
                        .WithMany("FunctionRoleMappings")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnomiAssignmentReal.Models.UserRole", "UserRole")
                        .WithMany("RoleFunctionPermissions")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.Category", b =>
                {
                    b.Navigation("CategoryMenuItems");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.Customer", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.CustomerOrder", b =>
                {
                    b.Navigation("CustomerOrderDetails");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.Function", b =>
                {
                    b.Navigation("FunctionRoleMappings");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.MenuItem", b =>
                {
                    b.Navigation("MenuItemCustomizations");

                    b.Navigation("MenuItemOrderDetails");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.OrderDetail", b =>
                {
                    b.Navigation("AppliedCustomizations");
                });

            modelBuilder.Entity("SnomiAssignmentReal.Models.UserRole", b =>
                {
                    b.Navigation("AssignedUsers");

                    b.Navigation("RoleFunctionPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
